import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../components/navigation/NavBar";
import Footer from "../components/footer/Footer";

const metadata: Metadata = {
  title: "SI Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />

      <main>{children}</main>

      <Footer />
    </>
  );
}
